#include <cstdint>  // Added for uint8_t and uint32_t
#include <iostream>
#include <ostream>
#include <vector>
#include <chrono>


// 1. The Core Engine Macros
#define VEObject(ClassName) \
class ClassName; /* Dummy tag for the template */ \
struct ClassName##_Schema

template <typename T>
class VReference;

template <typename T>
VReference<T> CreateVEObject() {
    // Calls the generated allocation function
    uint32_t newIndex = VReference<T>::AllocateInSoA();
    return VReference<T>(newIndex);
}

// 2. What the Developer Writes
VEObject(Player)
{
    int position;
    int health;
};

// ---------------------------------------------------------
// 3. GENERATED BY vbuild (Player.generated.h)
// ---------------------------------------------------------

class PlayerSchema
{
private:
    int _id;
    int _position;
    int _health;

public:
    PlayerSchema(uint32_t id) : _id(id), _position(0), _health(0) {};

    int& position() { return _position; }
    // The player's health
    int& health()   { return _health; }

    uint32_t GetID() const { return _id; }
};

struct PlayerSoA {
    std::vector<int> position;
    // The player's health
    std::vector<int> health;
};

// Global storage instance
PlayerSoA g_PlayerStorage;

template <>
class VReference<Player> {
private:
    uint32_t index;

public:
    VReference(uint32_t i) : index(i) {}

    // FIX 1: Provide the Allocate function that CreateVEObject expects
    static uint32_t AllocateInSoA() {
        uint32_t newIndex = g_PlayerStorage.position.size();
        g_PlayerStorage.position.push_back(0); // Default init
        g_PlayerStorage.health.push_back(0);   // Default init
        return newIndex;
    }

    // FIX 2: Replace operator-> with direct reference-returning methods
    int& position() { return g_PlayerStorage.position[index]; }
    // The player's health
    int& health()   { return g_PlayerStorage.health[index]; }

    uint32_t GetID() const { return index; }
};

// ---------------------------------------------------------
constexpr size_t OBJECTS_TO_GENERATE = 100000000;

void MassCreateSoA()
{
    std::string output;
    output.reserve(OBJECTS_TO_GENERATE * 60);
    for (int i = 1; i < OBJECTS_TO_GENERATE; i++)
    {
        VReference<Player> p = CreateVEObject<Player>();
        p.health() = i;
        output.append("Created game object with id ");
        output.append(std::to_string(p.GetID()));
        output.append(" with health ");
        output.append(std::to_string(p.health()));
        output.append("\n");
    }

    //std::cout << output << std::endl;
}

void MassCreateObjects()
{
    std::string output;
    output.reserve(OBJECTS_TO_GENERATE * 60);
    for (int i = 1; i < OBJECTS_TO_GENERATE; i++)
    {
        PlayerSchema *pptr = new PlayerSchema(i);
        PlayerSchema p = *pptr;
        p.health() = i;
        output.append("Created game object with id ");
        output.append(std::to_string(p.GetID()));
        output.append(" with health ");
        output.append(std::to_string(p.health()));
        output.append("\n");
    }

    //std::cout << output << std::endl;
}

auto main(int argc, char *argv[]) -> int {
    using clock = std::chrono::steady_clock;

    const auto soaStart = clock::now();
    MassCreateSoA();
    const auto soaEnd = clock::now();

    const auto objStart = clock::now();
    MassCreateObjects();
    const auto objEnd = clock::now();

    const auto soaMs =
        std::chrono::duration<double, std::milli>(soaEnd - soaStart).count();
    const auto objMs =
        std::chrono::duration<double, std::milli>(objEnd - objStart).count();

    std::cerr << "MassCreateSoA():     " << soaMs << " ms\n";
    std::cerr << "MassCreateObjects(): " << objMs << " ms\n";

    return 0;
}