name: Feature Request
description: Propose a new feature or enhancement
title: "[Feature Request]: "
type: Feature
body:
  - type: textarea
    id: story
    attributes:
      label: Story
      description: Provide the user story for this feature (e.g., "As a [role], I want to [action] so that [benefit]").
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe how the feature should work.
    validations:
      required: true